#!bin/bash

# make needed directories
mkdir /home/pi/.local
mkdir /home/pi/.local/resources

# copy the resource files to the directies
cp display.py /home/pi/.local/resources/
cp NotoMono-Regular.ttf /home/pi/.local/resources/

# add the display service to systemctl, so the display is updated on every restart of the raspi
cp inky_display.service /lib/systemd/system/
chmod 644 /lib/systemd/system/inky_display.service
systemctl daemon-reload
systemctl enable inky_display.service
