#!bin/bash

mkdir /home/pi/raspipgmlog/software/src/uploads
mkdir /home/pi/raspipgmlog/software/src/downloads
mkdir /home/pi/raspipgmlog/software/src/downloads/logs
mkdir /home/pi/raspipgmlog/software/src/downloads/read_files
mkdir /home/pi/raspipgmlog/software/src/downloads/timeplots
echo "copied source files"

chown -R pi:pi /home/pi/raspipgmlog/software/src
echo "adjusted ownerships"

chmod -R 777 /home/pi/raspipgmlog/software/src/upload
chmod -R 777 /home/pi/raspipgmlog/software/src/downloads
chmod -R 777 /home/pi/raspipgmlog/software/src/downloads/logs
chmod -R 777 /home/pi/raspipgmlog/software/src/downloads/read_files
chmod -R 777 /home/pi/raspipgmlog/software/src/downloads/timeplots
echo "adjusted rights"

cp node_server.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable node_server.service
systemctl start node_server.service
echo "setup node js server"
